docs/engines/manifest.md
Added supportedInputFormats as a required field
Added serverCountry as a new field
=> Updated manifest fields 

docs/engines/engine_standards/veri-standard-sample.js
This is my attempt to make the formatting and annotation of the sample
engine output JS file consistent and thereby draw out areas where
things are unclear or ambiguous.
=> [WIP] Clean up formatting and annotation of the sample JS file

package.json
To work with Jenkins after pipeline changes
=> move build directory to include environment for Jenkins pipeline

docs/engines/getting-started/technologies.md
Will describe Docker, share links to resources and describe how Docker is used on aiWARE.
=> add-docker-description-to-technologies-used

docs/engines/standards/vtn-standard.schema.json
Following Steve's suggestion I created some definitions for objects that are used more than once. It could make it easier to maintain the schema.
=> VTN-13068, add definitions to vtn standard

docs/_sidebar.md, docs/developer/engines/cognitive/biometrics/face-detection/README.md, docs/developer/engines/cognitive/biometrics/face-recognition/README.md, docs/developer/engines/cognitive/data/correlation/README.md, docs/developer/engines/cognitive/data/geolocation/README.md, docs/developer/engines/cognitive/speech/speaker-separation/README.md, docs/developer/engines/cognitive/vision/license-plate/README.md, docs/developer/engines/cognitive/vision/logo-detection/README.md, docs/developer/engines/cognitive/vision/object-detection/README.md, docs/developer/engines/standards/README.md
Just some last-minute review on the individual capability docs
=> VTN-14864 Clean up engine output docs

package.json
Pull Request opened by Jenkins script
=> Pull Request opened by Jenkins script

Dockerfile, buildinfo.sh, getconfig.sh
https://steel-ventures.atlassian.net/browse/VTN-19665
https://docs.zsc1.usgoveast1.veritone.com/#/ is working
=> changes to build docker image in azure(VTN-19665)

docs/apps/README.md
Ticket: https://steel-ventures.atlassian.net/browse/VTN-27938
=> VTN-27938 - Automate Studio in Apps Docs

docs/developer/flow/README.md, docs/developer/flow/faq.md
Some initial edits to "Flow docs" to
* normalize the name to Veritone Automate Studio
* delete content-free constructions
* insert helpful links to stuff
=> Feature/vtn 24166/flow docs kas edits

src/docs/apis/tutorials/README.md, src/docs/developer/engines/tutorial/engine-tutorial-step-5.md
No action needed on your part. I will manually merge.
=> VTN-30481 Add Deeper Dive to tutorials list

package.json, src/docs/_sidebar.md, src/scripts/docsifyConfig.js, src/styles/sidebar.scss, test/e2e/init.test.js, yarn.lock
Link to issue:  [https://steel-ventures.atlassian.net/browse/CXDX-234](https://steel-ventures.atlassian.net/browse/CXDX-234)
Fixed by removing `docsifyConfig.name` (only supports string anyways, was hacky to try and render HTML) and added a styled div with link inside `_sidebar.md`
=> Updated docsify, fixed logo issue displaying as raw html

src/docs/developer/flow/README.md
Enhancing the Automate docs with a section on debugging your workflows
=> AIW-1850 - Debugging your flows

src/docs/_coverpage.md
updating the What's New section with new line items
=> AIW-1094 - update what's new 2020-02-10

src/docs/developer/flow/README.md
ln # 25: aiAWARE -> aiWARE 
@kasthomas2 please approve 🙏
=> AIW-945 - Fix flow docs typo

src/docs/_coverpage.md
Update coverpage with header hyperlink for Automate Studio docs
=> AIW-2060 - Automate Studio docs

src/docs/_sidebar.md, src/docs/apis/eventing/eventing.md
New branch using the feature/* branch naming convention and consolidating the new file with the sidebar change 🤞
=> AIW-2352 - Eventing docs & sidebar

src/docs/developer/engines/standards/engine-output/vtn-standard.example.js
Issue: https://steel-ventures.atlassian.net/browse/VTN-36430
Reported this as while ago but just ran into it again. Now I know how to update the docs, so decided to just go ahead and fix it.
Kas, I introduced non-ASCII characters into the documentation. Please let me know if that is not acceptable and I will remove the box characters.
=> VTN-36430 Clarify polygon coordinate system

src/docs/apis/tutorials/asset-types.md
Document how to authorize a media-streamer URL
=> Add documentation on how to authorize media-streamer URLs

src/docs/cognitive-technology/cognitive/text/sentiment/README.md, src/docs/developer/engines/standards/engine-output/vtn-standard.example.js
https://github.com/veritone/aiware-core/issues/492
Standardize sentiment definitions to mean one thing. Describe how to map polarized sentiments to vtn-standard
=> veritione/aiware-core#492 Clarify sentiment, remove polarization

src/docs/aiware/manage/maintenance.md
Add helpful tips to manage engines and engine builds with aiWARE Anywhere.
=> Add Tips for Engine Maintenance with aiWARE
